import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/Navigation";
import Footer from "@/components/Footer";
import classNames from "classnames";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={classNames(inter.className)}>
        <Navigation />
        <div className={"flex flex-col h-[100%]"}>
          <main className={"mt-32 mr-60 ml-60 mb-20 flex-grow flex-shrink-0 basis-auto"}>
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
